cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    # url(r'^paypal/', include('paypal.standard.ipn.urls')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),
    # url(r'^', views.base, name='base'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

shop/urls.py
from django.conf.urls import url
from shop import views

app_name = 'something'
urlpatterns = [
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^$', views.ProductList, name='ProductList'),
]

common/views.py
from django.views.generic.base import ContextMixin
# from shop.models import Category
from django.shortcuts import render, get_object_or_404
from shop.models import Product, Category
from cart.forms import CartAddProductForm


class HeaderContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data.update({
            'categories': Category.objects.all(),
        })
        return data

def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'common/header.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

templates/common/footer.html
<!-- Origional snipet by msurguy<http://bootsnipp.com/msurguy>, I editted his snipet so that it works with bootstrap 3.3 -->
<div class="container cfooter footerSection">
    <div class="row">
            <div class="col-xs-8">
                <ul class="list-unstyled list-inline pull-left">
                    <li><a href="/" class='text-muted'>Главная</a></li>
                    <li><a href="#" class='text-muted'>Контакты</a></li>
                    <li><a href="#" class='text-muted'>Конфиденциальность</a></li>
                </ul>
            </div>
            <div class="col-xs-4">
                <p class="text-muted pull-right">© 2019 electronika corparation. All rights reserved</p>
            </div>
        </div>
</div>

templates/common/header.html
{% load static %}
<link rel="stylesheet" href="style.css" > 
<link rel="stylesheet" href="">
<nav class="navbar-fixed-top nav">
  <ul class="main">
    <li><a href="/">Главная</a></li>
    <li><a href="#">О нас</a></li>
    <li><img src="{% static "img/logo_1.png" %}" class="logo">
      <ul class="drop">
        <div>
          <li {% if not category %} class="selected" {% endif %}>
              <a href='{% url "shop:ProductList" %}'>Все</a>
          </li>
          {% for cat in categories %}
          <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
          </li>
          {% endfor %}
        </div>
      </ul>
    </li>
    <li> <a href="#">Контакты</a></li>
    <li><a href="{% url "cart:CartDetail" %}">Корзина
      <span class="badge">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
                {{ total_items }}
         {% else %}
              0
        {% endif %}
        {% endwith %} 
      </span>
    </a></li>
  </ul>
</nav>
{% comment %}  
<nav id='nav' class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><img src="{% static "img/logo.png" %}" class="logo" ></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">Главная<span class="sr-only">(current)</span></a></li>
        <li ><a href="company.html">О нас<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Контакты</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Категории<span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li {% if not category %} class="selected" {% endif %}>
                <a href='{% url "shop:ProductList" %}'>Все</a>
              </li>
            {% for cat in categories %}
              <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
              <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url "cart:CartDetail" %}">
      <button class="btn btn-default" type="submit" style= 'margin:-10px;'> 
        Корзина:
        {% with total_items=cart|length %}
        
        {% if cart|length > 0 %}
            {% comment %} <img src='{%static "img/cart.png" %}' class='cart_icon'>:
                {{ total_items }}
         {% else %}
              0
        {% endif %}
        {% endwith %}
        </button></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>{% endcomment %}